### ISSUE TITLE
Add Profile to ROS-Industrial GH Org

### ISSUE THREAD

**Issue by robinsonmm** [ros-industrial/.github#1]
# ROS-Industrial

Welcome to the ROS-Industrial GitHub organization.

## Purpose

The ROS-Industrial open source project is seeks to provide modules and resource to enable industrial relevant hardware, tools and application leveraging the ROS ecosystem. The purpose of this organization is to track foundational capabilities and resources that are community leveraged, maintained and fully open source. This GitHub organization supports both community and consortia generated projects, modules and resources to enable industrial leverage of ROS and ROS 2 specifically, in industrial settings.

ROS-Industrial is not a replacement for ROS but is intended to work within the ROS ecosystem. The strategy has been to provide utilities and resources in a ROS agnostic way to provide those interested in leveraging ROS and ROS 2 resources in the way that meets their needs. Many of the core developed resources are ROS agnostic with ROS or ROS 2 wrappers provided. In some cases specific ROS and ROS 2 versions are maintained and this is determined based on the nature of the resource and how it interacts with the ROS or ROS 2 ecosystem.

You can learn more about ROS-Industrial, the Consortia that support the project and other GitHub organizations over at www.rosindustrial.org.

## Status of repositories

In all cases in this organization these projects are open source and business friendly licensed. All the repositories herein are actively supported, by the supporting teams, and participants in the ROS-I open source project community along with the supporting consortia organizations of the specific project.

## Issue trackers and Pull Requests

We welcome engagement with the projects via issue trackers and welcome pull requests and discussions around the future projection and opportunities for improvement of any the projects within the organization.

**Comment by robinsonmm** [comment]
Draft 0

**Comment by gavanderhoorn** [comment]
Hi @robinsonmm. Thanks for this.

Would you want me to create a PR for this, so it can be reviewed there?

Or will you add it as in [ros-industrial-consortium/.github](https://github.com/ros-industrial-consortium/.github)?

**Comment by robinsonmm** [comment]
It just showed the repo as empty with no option to fork or create a PR, so I at least wanted to get this up here.

Also, I believe there is a /profile then this markdown content.

**Comment by gavanderhoorn** [comment]
See #2.

**Comment by gavanderhoorn** [comment]
Closing in favour of #2.
